- name: Template Provisioning
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - variables-vault.yaml
    - variables.yaml
  tasks:
  - name: Satellite - Create New Host for rhv
    tags: newvm
    local_action: uri
    args:
      url: "{{ sat_url_newhost }}"
      user: "{{ sat_username }}"
      password: "{{ sat_password }}"
      force_basic_auth: true
      return_content: true
      validate_certs: false
      body_format: json
      method: POST
      body:
        host: "{{ template }}"
      status_code:
      - 201
      - 422
    changed_when: host_create_rhv.status == 201
    failed_when:
    - host_create_rhv.status != 201
    - host_create_rhv.status != 422
    - host_create_rhv.json.error.errors.name[0] != "has already been taken"
    register: host_create_rhv

  - name: Generate hosts-templaterhv file
    copy:
      dest: hosts-templaterhv
      content: |
        [templaterhv]
        {{ template.name }} ansible_ssh_host={{ template.ip }} ansible_ssh_user=root ansible_password={{ vm_password }}

