- name: Template Provisioning
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - variables-vault.yaml
    - variables.yaml
  tasks:

  - name: Search hostgroup in Satellite - vmware
    local_action: uri
    args:
      url: "{{ sat_server_url }}/api/hostgroups?search={{ template_vmware.hostgroup_name|urlencode }}"
      user: "{{ sat_username }}"
      password: "{{ sat_password }}"
      force_basic_auth: true
      return_content: true
      validate_certs: false
      body_format: json
      method: GET
    register: json_response_vmware

  - name: Loop for hostgroup id
    set_fact:
      dyn_hostgroup_id: "{{ item.id }}"
    loop: "{{ json_response_vmware.json.results }}"
    loop_control:
      label: "{{ item.name }}"
    when: json_response_vmware.json['results'][0]['id'] is defined and item.name == template_vmware.hostgroup_name

  - name: Exit if hostgroup name is not found
    fail:
      msg: "Hostgroup name '{{ template_vmware.hostgroup_name }}' not found... Exit"
    when:
      - dyn_hostgroup_id is undefined

  - name: Satellite - Create New Host for vmware
    tags: newvm
    local_action: uri
    args:
      url: "{{ sat_url_newhost }}"
      user: "{{ sat_username }}"
      password: "{{ sat_password }}"
      force_basic_auth: true
      return_content: true
      validate_certs: false
      body_format: json
      method: POST
      body:
        host: "{{ template_vmware }}"
      status_code:
      - 201
      - 422
    changed_when: host_create_vmware.status == 201
    failed_when:
    - host_create_vmware.status == 422
    - host_create_vmware.json.error.full_messages[0] is defined and host_create_vmware.json.error.full_messages[0] != "Name has already been taken"
    register: host_create_vmware

  #- debug:
  #    var: host_create_vmware

  - name: Generate hosts-templatevmware file
    copy:
      dest: hosts-templatevmware
      content: |
        [templatevmware]
        {{ template_vmware.name }} ansible_ssh_host={{ template_vmware.ip }} ansible_ssh_user=root ansible_password={{ vm_password }}

