- name: Template Provisioning
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - variables-vault.yaml
    - variables.yaml
  tasks:
  - name: Satellite - Create New Host for VMware
    tags: newvm
    local_action: uri
    args:
      url: "{{ sat_url_newhost }}"
      user: "{{ sat_username }}"
      password: "{{ sat_password }}"
      force_basic_auth: true
      return_content: true
      validate_certs: false
      body_format: json
      method: POST
      body:
        host: "{{ template_vmware }}"
      status_code:
      - 201
      - 422
    changed_when: host_create_vmware.status == 201
    failed_when:
    - host_create_vmware.status != 201
    - host_create_vmware.status != 422
    - host_create_vmware.json.error.errors.name[0] != "has already been taken"
    register: host_create_vmware

  - name: Generate hosts-templatevmware file
    copy:
      dest: hosts-templatevmware
      content: |
        [templatevmware]
        {{ template_vmware.name }} ansible_ssh_host={{ template_vmware.ip }} ansible_ssh_user=root ansible_password={{ vm_password }}

