- name: Template Customization
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - variables-vault.yaml
    - variables.yaml
  tasks:
  - name: Add vm host
    add_host:
      name: "{{ engine_template.name }}"
      #ansible_ssh_private_key_file: ansible-ssh/id_rsa
      ansible_ssh_user: root
      ansible_password: "{{ vm_password }}"
      ansible_ssh_host: "{{ template.ip }}"
      groups:
        - templaterhv
    changed_when: False

- name: Wait for the vm to be online
  hosts: templaterhv
  gather_facts: True
  vars_files:
    - variables-vault.yaml
    - variables.yaml
  tasks:
  - name: Set hostname
    hostname:
      name: localhost.localdomain

  - name: Reset machine id
    copy:
      dest: /etc/machine-id
      content: ""
      mode: "0777"

  - name: Remove /var/lib/dbus/machine-id
    file:
      path: /var/lib/dbus/machine-id
      state: absent

  - name: Unregister
    redhat_subscription:
      state: absent

  - name: Remove katello-ca-consumer
    dnf:
      name: katello-ca-consumer*
      state: absent

  - name: Remove /etc/rhsm/facts/katello.facts
    file:
      path: /etc/rhsm/facts/katello.facts
      state: absent

  - name: dnf clean
    command: dnf clean all

  - name: Remove log files
    shell: rm -rf {{ item }}
    with_items:
      - "/etc/Pegasus/*.cnf"
      - "/etc/Pegasus/*.crt"
      - "/etc/Pegasus/*.csr"
      - "/etc/Pegasus/*.pem"
      - "/etc/Pegasus/*.srl"
      - "/root/anaconda-ks.cfg"
      - "/root/anaconda-post.log"
      - "/root/initial-setup-ks.cfg"
      - "/root/install.log"
      - "/root/install.log.syslog"
      - "/root/original-ks.cfg"
      - "/var/cache/fontconfig/*"
      - "/var/cache/gdm/*"
      - "/var/cache/man/*"
      - "/var/lib/AccountService/users/*"
      - "/var/lib/fprint/*"
      - "/var/lib/logrotate.status"
      - "/var/log/*.log*"
      - "/var/log/BackupPC/LOG"
      - "/var/log/ConsoleKit/*"
      - "/var/log/anaconda.syslog"
      - "/var/log/anaconda/*"
      - "/var/log/apache2/*_log"
      - "/var/log/apache2/*_log-*"
      - "/var/log/apt/*"
      - "/var/log/aptitude*"
      - "/var/log/audit/*"
      - "/var/log/btmp*"
      - "/var/log/ceph/*.log"
      - "/var/log/chrony/*.log"
      - "/var/log/cron*"
      - "/var/log/cups/*_log*"
      - "/var/log/debug*"
      - "/var/log/dmesg*"
      - "/var/log/exim4/*"
      - "/var/log/faillog*"
      - "/var/log/firewalld*"
      - "/var/log/gdm/*"
      - "/var/log/glusterfs/*glusterd.vol.log"
      - "/var/log/glusterfs/glusterfs.log"
      - "/var/log/grubby*"
      - "/var/log/httpd/*log"
      - "/var/log/installer/*"
      - "/var/log/jetty/jetty-console.log"
      - "/var/log/journal/*"
      - "/var/log/lastlog*"
      - "/var/log/libvirt/libvirtd.log"
      - "/var/log/libvirt/libxl/*.log"
      - "/var/log/libvirt/lxc/*.log"
      - "/var/log/libvirt/qemu/*.log"
      - "/var/log/libvirt/uml/*.log"
      - "/var/log/lightdm/*"
      - "/var/log/mail/*"
      - "/var/log/maillog*"
      - "/var/log/messages*"
      - "/var/log/ntp"
      - "/var/log/ntpstats/*"
      - "/var/log/ppp/connect-errors"
      - "/var/log/rhsm/*"
      - "/var/log/sa/*"
      - "/var/log/secure*"
      - "/var/log/setroubleshoot/*.log"
      - "/var/log/spooler*"
      - "/var/log/squid/*.log"
      - "/var/log/syslog*"
      - "/var/log/tallylog*"
      - "/var/log/tuned/tuned.log"
      - "/var/log/wtmp*"
      - "/var/log/xferlog*"
      - "/var/named/data/named.run"
      - "/root/.bash_history"
      - "/home/*/.bash_history"
      - "/etc/group-"
      - "/etc/gshadow-"
      - "/etc/passwd-"
      - "/etc/shadow-"
      - "/etc/subgid-"
      - "/etc/subuid-"
      - "/var/lib/rpm/__db.*"
      - "/root/.ssh"
      - "/home/*/.ssh"
      - "/etc/ssh/ssh_host_*"
      - "/etc/sysconfig/network-scripts/ifcfg-*"
      - "/etc/udev/rules.d/70-persistent-*"
      - "/var/lib/cloud/*"
      - "/var/run/utmp"

  - name: Remove tmp files
    shell: rm -rf {{ item }}
    with_items:
      - "/tmp/*"
      - "/var/tmp/*"
